version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  wordpress: 
    image: wordpress:latest
    container_name: wordpress_app
    depends_on: 
      - db
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://ghastly-owl-x5wq5757v955c9xpw-8080.app.github.dev');
        define('WP_SITEURL', 'https://ghastly-owl-x5wq5757v955c9xpw-8080.app.github.dev');
    volumes:
      - ./wordpress_data:/var/www/html

volumes:
  db_data:

   
